export const blogItems = [
  {
    date: "Monday 05, September 2021 ",
    authorName: "Jamal Khan",
    title: "Dementia: Dementia and sleep: What do we know about this link?",
    views: "68",
    reaction: "86",
    id: "1",
  },
  {
    date: "Monday 06, September 2021 ",
    authorName: "Jamal Khan",
    title: "Anxiety:Anxiety in men: Fighting stereotypes",
    views: "68",
    reaction: "86",
    id: "2",
  },
  {
    date: "Monday 07, September 2021 ",
    authorName: "Jamal Khan",
    title:
      "Alzheimer’s: 6 aspects of the condition that are often misunderstood",
    views: "68",
    reaction: "86",
    id: "3",
  },
  {
    date: "Monday 08, September 2021 ",
    authorName: "Jamal Khan",
    title: "COVID: Long COVID still a risk, even for vaccinated people",
    views: "68",
    reaction: "86",
    id: "4",
  },
  {
    date: "Monday 09, September 2021 ",
    authorName: "Jamal Khan",
    title: " COVID: What we know about a new coronavirus spreading in voles",
    views: "68",
    reaction: "86",
    id: "5",
  },
  {
    date: "Monday 10, September 2021 ",
    authorName: "Jamal Khan",
    title:
      "Lung cancer: Drug combo improves survival rate without chemotherapy",
    views: "68",
    reaction: "86",
    id: "6",
  },
  {
    date: "Monday 11, September 2021 ",
    authorName: "Jamal Khan",
    title: "This Article’s Title goes Here, but not too long",
    views: "68",
    reaction: "86",
    id: "7",
  },
  {
    date: "Monday 12, September 2021 ",
    authorName: "Jamal Khan",
    title: "2 male contraceptive pills show promise in early studies",
    views: "68",
    reaction: "86",
    id: "8",
  },
  {
    date: "Monday 13, September 2021 ",
    authorName: "Jamal Khan",
    title: "Probiotics: Could good gut bacteria help tackle depression?",
    views: "68",
    reaction: "86",
    id: "9",
  },
  {
    date: "Monday 14, September 2021 ",
    authorName: "Jamal Khan",
    title: "2-3 cups of coffee a day may reduce kidney injury risk by 23%",
    views: "68",
    reaction: "86",
    id: "10",
  },
  {
    date: "Monday 15, September 2021 ",
    authorName: "Jamal Khan",
    title: "The best exercise time is different for men and women, study finds",
    views: "68",
    reaction: "86",
    id: "11",
  },
  {
    date: "Monday 16, September 2021 ",
    authorName: "Jamal Khan",
    title: "Transgender teens 7.6 times more likely to attempt suicide",
    views: "68",
    reaction: "86",
    id: "12",
  },
];
